image: maven:3.8.3-openjdk-17

stages:
  - test
  - build

variables:
  MAVEN_OPTS: "-Djava.awt.headless=true -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
  MAVEN_CLI_OPTS: "--batch-mode -P headless -DskipUiTests=true"

test:
  stage: test
  script:
    - echo "Starter tester"
    - cd app-gruppe36
    - mvn clean test $MAVEN_CLI_OPTS

build:
  stage: build
  script:
    - echo "Starter bygging"
    - cd app-gruppe36
    - mvn clean install $MAVEN_CLI_OPTS

  when: manual
