image: maven:3.8.3-openjdk-17

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
  MAVEN_CLI_OPTS: "--batch-mode"

stages:
  - build
  - test

cache:
  paths:
    - .m2/repository
  key: "$CI_BUILD_REF_NAME"

before_script:
  - apt-get update && apt-get install -y libx11-6 libxext6 libxrender1 libxtst6 libxi6 libfreetype6 xvfb

test:
  stage: test
  script:
    - cd app-gruppe36
    - mvn clean test $MAVEN_CLI_OPTS

build:
  stage: build
  when: manual
  script:
    - cd app-gruppe36
    - mvn clean install $MAVEN_CLI_OPTS
