image: maven:3.8.3-openjdk-17

variables:
  MAVEN_CLI_OPTS: "--batch-mode"

before_script:
  cd app-gruppe36

stages:
  - compile
  - install
  - test
cache:
  key: "${CI_COMMIT_REF_SLUG}"
  paths:
    - .m2/repository


test:
  stage: test
  script:
    - echo "GIKK INN I TEST"
    - mvn $MAVEN_CLI_OPTS -Dui.skip.tests=true test

    
compile:
  stage: compile
  script:
    - mvn clean compile

install:
  stage: install
  script:
    - mvn install -DskipTests

