image: maven:3.8.3-openjdk-17

variables:
  MAVEN_OPTS: "-Djava.awt.headless=true -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

stages:
  - test

cache:
  paths:
    - .m2/repository
  key: "$CI_BUILD_REF_NAME"

test:
  stage: test
  script:
    - "cd app-gruppe36; mvn clean test"
