image: maven:3.8.3-openjdk-17

variables:
  MAVEN_CLI_OPTS: "--batch-mode"

before_script:
  cd app-gruppe36

stages:
  - compile

cache:
  key: "${CI_COMMIT_REF_SLUG}"
  paths:
    - .m2/repository


test:
  stage: test
  script:
    - echo "GIKK INN I TEST"
    - mvn test $MAVEN_CLI_OPTS -DskipUiTests=true

compile:
  stage: compile
  script:
    - mvn clean compile
