image: maven:3.8.3-openjdk-17

variables:
  MAVEN_CLI_OPTS: "--batch-mode"

before_script: cd app-gruppe36

stages:
  - compile
  - test
  - install
cache:
  key: "${CI_COMMIT_REF_SLUG}"
  paths:
    - .m2/repository

compile:
  stage: compile
  script:
    - mvn clean compile

test:
  stage: test
  script:
    - echo "Kj√∏rer tester utenom spesifikke filer i model-mappen"
    - mvn $MAVEN_CLI_OPTS -pl '!view' clean test -DexcludeTests="model.WasteModelTest,model.MenueViewModelTest,model.WashingPlanModelTest"

install:
  stage: install
  script:
    - mvn clean install -DskipTestss
