image: maven:3.11-openjdk-17

stages:
  - test
  - build

variables:
  MAVEN_OPTS: "-Djava.awt.headless=true -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
  MAVEN_CLI_OPTS: "--batch-mode -P headless -DskipUiTests=true"

cache:
  paths:
    - .m2/repository
  key: "$CI_COMMIT_REF_NAME"

test:
  stage: test
  script:
    - echo "Starter tester med Maven 3.11 og Java 17"
    - cd app-gruppe36
    - mvn clean test $MAVEN_CLI_OPTS

build:
  stage: build
  script:
    - echo "Starter bygging med Maven 3.11 og Java 17"
    - cd app-gruppe36
    - mvn clean install $MAVEN_CLI_OPTS

  when: manual
