image: maven:3.8.3-openjdk-17

variables:
  MAVEN_CLI_OPTS: "--batch-mode"

before_script:
  cd app-gruppe36

stages:
  - compile
  - test
  - install
cache:
  key: "${CI_COMMIT_REF_SLUG}"
  paths:
    - .m2/repository

test:
  stage: test
  script:
    - echo "Kj√∏rer tester utenom UI"
    - mvn $MAVEN_CLI_OPTS -pl '!view' clean test -DexcludeTests="model.WashingPlanModelTest,model.WasteModelTest,MenueViewModelTest"

compile:
  stage: compile
  script:
    - mvn clean compile

install:
  stage: install
  script:
    - mvn clean install -DskipTests